import { createThemePlugin } from '@vuetify/v0'

export default createThemePlugin({
  default: 'dark',
  target: 'html',
  themes: {
    light: {
      dark: false,
      colors: {
        'primary': '#E6A82D',
        'secondary': '#0041FF',
        'error': '#ef4444',
        'info': '#38bdf8',
        'success': '#22c55e',
        'warning': '#fb923c',
        'background': '#f5f5f5',
        'surface': '#ffffff',
        'surface-tint': '#f5f5f5',
        'surface-variant': '#eeeeee',
        'divider': '#e0e0e0',
        'on-primary': '#06101d',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-info': '#1a1a1a',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#212121',
        'on-surface': '#212121',
        'on-surface-variant': '#666666',
      },
    },
    dark: {
      dark: true,
      colors: {
        'primary': '#E6A82D',
        'secondary': '#0041FF',
        'error': '#fb7185',
        'info': '#38bdf8',
        'success': '#22c55e',
        'warning': '#fbbf24',
        'background': '#090b12',
        'surface': '#121722',
        'surface-tint': '#1b2233',
        'surface-variant': '#1d2636',
        'divider': '#2a3447',
        'on-primary': '#06101d',
        'on-secondary': '#ffffff',
        'on-error': '#1a1a1a',
        'on-info': '#1a1a1a',
        'on-success': '#1a1a1a',
        'on-warning': '#1a1a1a',
        'on-background': '#f8fafc',
        'on-surface': '#f8fafc',
        'on-surface-variant': '#94a3b8',
      },
    },
  },
})
