/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/attendance/': RouteRecordInfo<
      '/admin/attendance/',
      '/admin/attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/attendance/[id]/': RouteRecordInfo<
      '/admin/attendance/[id]/',
      '/admin/attendance/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/attendance/[id]/edit': RouteRecordInfo<
      '/admin/attendance/[id]/edit',
      '/admin/attendance/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/members': RouteRecordInfo<
      '/admin/members',
      '/admin/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/overview': RouteRecordInfo<
      '/admin/overview',
      '/admin/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/token-ledger': RouteRecordInfo<
      '/admin/token-ledger',
      '/admin/token-ledger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/profile': RouteRecordInfo<
      '/dashboard/profile',
      '/dashboard/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[id]': RouteRecordInfo<
      '/projects/[id]',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/attendance/index.vue': {
      routes:
        | '/admin/attendance/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/attendance/[id]/index.vue': {
      routes:
        | '/admin/attendance/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/attendance/[id]/edit.vue': {
      routes:
        | '/admin/attendance/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/members.vue': {
      routes:
        | '/admin/members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/overview.vue': {
      routes:
        | '/admin/overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/token-ledger.vue': {
      routes:
        | '/admin/token-ledger'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/profile.vue': {
      routes:
        | '/dashboard/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id].vue': {
      routes:
        | '/projects/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
