name: Docker Image CI

on:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          tag=${{ github.ref_name }}
          short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
          if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --file Dockerfile \
              --build-arg VERSION=${{ github.ref_name }} \
              --build-arg COMMIT=${short_sha} \
              --tag ghcr.io/sol-armada/website:latest \
              --tag ghcr.io/sol-armada/website:${{ github.ref_name }} \
              --push \
              .
          else
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --file Dockerfile \
              --build-arg VERSION=${{ github.ref_name }} \
              --build-arg COMMIT=${short_sha} \
              --tag ghcr.io/sol-armada/website:${{ github.ref_name }} \
              --push \
              .
          fi
